### ISSUE TITLE
[release-4.14] crc start fails when using an ocp pre-release vesion 4.14.0-rc.X

### ISSUE THREAD

**Issue by adrianriobo** [crc-org/crc#3883] opened 2023-10-19 11:06 UTC
During the pre-release testing for ocp 4.14 `crc start` exists with failure:

```
INFO Waiting for kube-apiserver availability... [takes around 2min] 
ssh command error:
command : timeout 30s oc delete -n openshift-machine-config-operator configmap machine-config-controller --context admin --cluster crc --kubeconfig /opt/kubeconfig
err     : Process exited with status 1
```

It seems the configmap does not exist within the mco version on ocp 4.14

**Comment by jsliacan** [comment] 2023-10-20 10:39
Turns out this was caused by using old test code. It does not happen when using e.g. latest e2e image v2.28.0.

**Comment by praveenkumar** [comment] 2023-10-20 10:41
This was not with the old test code but I created #3886 for same.

**Comment by adrianriobo** [comment] 2023-10-20 10:49
yeah this comments should go on #3882 to close it

**Comment by jsliacan** [comment] 2023-10-20 10:51
Yes yes, thanks for noticing. We were discussing an issue where 4.14 bundle wasn't used even if provided by the user. Then I just closed this with that version in the title... My bad. Sorry.

**Closed as completed** 2023-11-07 04:42 UTC
Labels: kind/enhancement, priority/major, os/linux, os/windows, os/macos, preset/openshift
