### ISSUE TITLE
[BUG] Can not find ndb-operator under community operator inside the CRC 

### ISSUE THREAD

**Issue by dineshsuryaprakash** [crc-org/crc#3947] opened 2023-12-13 16:25 UTC
### General information

  * OS: Linux 
  * Hypervisor: KVM
  * Did you run `crc setup` before starting it (Yes/No)? no
![Screenshot from 2023-12-13 21-54-06](https://github.com/crc-org/crc/assets/105935460/51d002c9-057c-4796-bbad-51b0c33c5586)

  * Running CRC on: Laptop 

## CRC version
CRC version: 2.30.0+b6532a
OpenShift version: 4.14.3
Podman version: 4.4.4

  
## CRC status
crc status --log-level debug
DEBU CRC version: 2.30.0+b6532a                   
DEBU OpenShift version: 4.14.3                    
DEBU Podman version: 4.4.4                        
DEBU Running 'crc status'                         
CRC VM:          Running
OpenShift:       Running (v4.14.3)
RAM Usage:       8.147GB of 16.76GB
Disk Usage:      26.7GB of 32.68GB (Inside the CRC VM)
Cache Usage:     23.28GB
Cache Directory: /home/dsprakas/.crc/cache

## CRC config
- consent-telemetry                     : no
- memory                                : 12288

## Host Operating System
PRETTY_NAME="Ubuntu 23.04"
NAME="Ubuntu"
VERSION_ID="23.04"
VERSION="23.04 (Lunar Lobster)"
VERSION_CODENAME=lunar
ID=ubuntu
ID_LIKE=debian
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
UBUNTU_CODENAME=lunar
LOGO=ubuntu-logo

### Steps to reproduce

  1. crc start
  2. 
  3. 
  4. 

### Expected
There are 337 operators in operatorhub.io and expect all of them in the operatorhub tab in the CRC console. 

### Actual
But CRC has only 228 community operators in it. If not for all i am interested at least with ndb-operator

**Comment by anjannath** [comment] 2023-12-13 18:18
@dineshsuryaprakash CRC does not make any changes to the operator hub, if possible could you please check if a normal OpenShift installation contains the operator you are interested in?

**Comment by gbraad** [comment] 2023-12-14 04:45
Searching for https://operatorhub.io/?keyword=ndb results in the page: https://operatorhub.io/operator/ndb-operator that explains how to install.
And also: https://github.com/nutanix-cloud-native/ndb-operator?tab=readme-ov-file#on-openshift only mentions to install using the operator-sdk ?

The difference might be related to the fact some of the operators might need more information provided to operate inside a cluster. Although, I can't say, never used this.

**Comment by gbraad** [comment] 2023-12-14 04:51
How many Database related items do show up in the cluster's view of the OperatorHub?

**Comment by dineshsuryaprakash** [comment] 2023-12-14 04:55
I can see 20 community operators in the cluster's view of the OperatorHub. But OperatorHub.io
![Screenshot from 2023-12-14 10-23-51](https://github.com/crc-org/crc/assets/105935460/77946df2-0a1f-4696-8a45-6c66abac369b)
 has 47 items

**Comment by gbraad** [comment] 2023-12-14 05:04
Something in that case filters, but we do not have control over this.
If you have access to an actual cluster, can you verify the behavior?

**Comment by dineshsuryaprakash** [comment] 2023-12-14 05:04
I have also tried to create the subscription for the ndb-operator as described in https://operatorhub.io/install/ndb-operator.yaml. But that did not work either. 
![Screenshot from 2023-12-14 10-33-59](https://github.com/crc-org/crc/assets/105935460/45f4f99f-31e7-4e24-91fa-8c853caff089)

**Comment by gbraad** [comment] 2023-12-14 05:08
I see @dineshsuryaprakash also actually provides the ndb-operator, as can be seen here: https://github.com/k8s-operatorhub/community-operators/tree/main/operators/ndb-operator/1.2.0 Best to ask someone else about this, as we do not customize or modify anything when it comes to offering the operatorhub.

**Comment by gbraad** [comment] 2023-12-14 05:12
Since many operators seem to show the same behavior, I believe it might be related to provided metadata?

Again, try to reproduce this on an actual cluster and confirm this is not CRC specific. Please consider filing an issue with: https://github.com/openshift/console/issues?

**Comment by praveenkumar** [comment] 2023-12-14 06:35
On production/actual cluster I don't see `ndb` operator listed so I don't think it is issue with CRC and closing this issue.

![Screenshot from 2023-12-14 12-04-33](https://github.com/crc-org/crc/assets/410007/3893f793-7a34-4dd3-abc0-626301d2057d)

**Closed as completed by praveenkumar** 2023-12-14 06:35 UTC
Labels: resolution/invalid, kind/question
