### ISSUE TITLE
Why isn't the OpenShift Cluster automatically started after Virtual Machine reboot?

### ISSUE THREAD

**Issue by ryanlyy** [crc-org/crc#3807] opened 2023-08-28 08:05 UTC
### General information

  * OS: Linux 
  * Hypervisor: KVM
  * Did you run `crc setup` before starting it (Yes/No): Yes
  * Running CRC on: VM

## CRC version
```bash
# Put `crc version` output here
CRC version: 2.24.1+81aeeb
OpenShift version: 4.13.6
Podman version: 4.4.4
```
  
## CRC status
```bash
# Put `crc status --log-level debug` output here
DEBU CRC version: 2.24.1+81aeeb
DEBU OpenShift version: 4.13.6
DEBU Podman version: 4.4.4
DEBU Running 'crc status'
CRC VM:          Stopped
OpenShift:       Stopped (v4.13.6)
RAM Usage:       0B of 0B
Disk Usage:      0B of 0B (Inside the CRC VM)
Cache Usage:     20.84GB

```

## CRC config
```bash
# Put `crc config view` output here
[ryanlyy@localhost ~]$ crc config view
- consent-telemetry                     : no
- http-proxy                            : http://ip:port/
- https-proxy                           : http://ip:port/
- no-proxy                              : 127.0.0.1,10.217.0.0/22,10.217.4.0/23,192.168.126.0/24,10.0.0.0/8,192.168.130.0/24,10.67.34.18/32,localhost,
- pull-secret-file                      : /home/ryanlyy/osl/pull-secret.txt
[ryanlyy@localhost ~]$
```

## Host Operating System
~Rocky Linux 9~ EL9 compatible

### Steps to reproduce

  1. Install CRC in Linux VM
  2. shutdown VM
  3. start VM
  4. CRC VM/Openshift: Stopped

### Expected
CRC VM/Openshift can be started automatically after start VM

### Actual
CRC VM/Openshfit is in Stopped status

**Comment by gbraad** [comment] 2023-08-28 08:08
If you mean that the cluster does not automagically start when the VM is restarted? This is by design, as we have to prepare the cluster environment before it gets started.

If this is an existing VM, you could suffice by logging in and starting the appropriate systemd service. Although, settings like no-proxy will not be passed into the VM that way.

In short; CRC as a tool is responsible for the lifecycle of the VM and the cluster, and ensuring settings are committed; like no-proxy, disk-size, certificates, etc.

**Closed as completed** 2023-08-28 08:16 UTC
Labels: resolution/invalid, kind/question
